spring.application.name=scalable-search-engine

spring.datasource.url=jdbc:postgresql://localhost:5432/scalable_search_engine
spring.datasource.username=postgres
spring.datasource.password=Dheeraj@2026

spring.jpa.hibernate.ddl-auto=update
server.port=8081
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true